/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n3.2.11-1-gc773ce32e1"
#endif /* AVUTIL_FFVERSION_H */
